// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: grpc_gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	golang "search/proto/golang"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchGateway_SearchGame_FullMethodName = "/gateway.SearchGateway/SearchGame"
)

// SearchGatewayClient is the client API for SearchGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// REST gateway service (HTTP → gRPC)
type SearchGatewayClient interface {
	SearchGame(ctx context.Context, in *golang.SearchGameRequest, opts ...grpc.CallOption) (*golang.SearchGameResponse, error)
}

type searchGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchGatewayClient(cc grpc.ClientConnInterface) SearchGatewayClient {
	return &searchGatewayClient{cc}
}

func (c *searchGatewayClient) SearchGame(ctx context.Context, in *golang.SearchGameRequest, opts ...grpc.CallOption) (*golang.SearchGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(golang.SearchGameResponse)
	err := c.cc.Invoke(ctx, SearchGateway_SearchGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchGatewayServer is the server API for SearchGateway service.
// All implementations must embed UnimplementedSearchGatewayServer
// for forward compatibility.
//
// REST gateway service (HTTP → gRPC)
type SearchGatewayServer interface {
	SearchGame(context.Context, *golang.SearchGameRequest) (*golang.SearchGameResponse, error)
	mustEmbedUnimplementedSearchGatewayServer()
}

// UnimplementedSearchGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchGatewayServer struct{}

func (UnimplementedSearchGatewayServer) SearchGame(context.Context, *golang.SearchGameRequest) (*golang.SearchGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGame not implemented")
}
func (UnimplementedSearchGatewayServer) mustEmbedUnimplementedSearchGatewayServer() {}
func (UnimplementedSearchGatewayServer) testEmbeddedByValue()                       {}

// UnsafeSearchGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchGatewayServer will
// result in compilation errors.
type UnsafeSearchGatewayServer interface {
	mustEmbedUnimplementedSearchGatewayServer()
}

func RegisterSearchGatewayServer(s grpc.ServiceRegistrar, srv SearchGatewayServer) {
	// If the following call panics, it indicates UnimplementedSearchGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchGateway_ServiceDesc, srv)
}

func _SearchGateway_SearchGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(golang.SearchGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchGatewayServer).SearchGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchGateway_SearchGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchGatewayServer).SearchGame(ctx, req.(*golang.SearchGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchGateway_ServiceDesc is the grpc.ServiceDesc for SearchGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.SearchGateway",
	HandlerType: (*SearchGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchGame",
			Handler:    _SearchGateway_SearchGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_gateway.proto",
}
