// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: grpc-gateway.proto

package golang

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	golang "search/proto/golang"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpc_gateway_proto protoreflect.FileDescriptor

const file_grpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\x12grpc-gateway.proto\x12\agateway\x1a\x1cgoogle/api/annotations.proto\x1a\x19search/proto/search.proto2r\n" +
	"\rSearchGateway\x12a\n" +
	"\n" +
	"SearchGame\x12\x1b.searchpb.SearchGameRequest\x1a\x1c.searchpb.SearchGameResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/search/gamesB\x1bZ\x19grpc-gateway/proto/golangb\x06proto3"

var file_grpc_gateway_proto_goTypes = []any{
	(*golang.SearchGameRequest)(nil),  // 0: searchpb.SearchGameRequest
	(*golang.SearchGameResponse)(nil), // 1: searchpb.SearchGameResponse
}
var file_grpc_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.SearchGateway.SearchGame:input_type -> searchpb.SearchGameRequest
	1, // 1: gateway.SearchGateway.SearchGame:output_type -> searchpb.SearchGameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_gateway_proto_init() }
func file_grpc_gateway_proto_init() {
	if File_grpc_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_gateway_proto_rawDesc), len(file_grpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_gateway_proto_goTypes,
		DependencyIndexes: file_grpc_gateway_proto_depIdxs,
	}.Build()
	File_grpc_gateway_proto = out.File
	file_grpc_gateway_proto_goTypes = nil
	file_grpc_gateway_proto_depIdxs = nil
}
