// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: search.proto

package golang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchSearchService_GetMatch_FullMethodName = "/MatchSearchService/GetMatch"
)

// MatchSearchServiceClient is the client API for MatchSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchSearchServiceClient interface {
	GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchResponse, error)
}

type matchSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchSearchServiceClient(cc grpc.ClientConnInterface) MatchSearchServiceClient {
	return &matchSearchServiceClient{cc}
}

func (c *matchSearchServiceClient) GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchResponse)
	err := c.cc.Invoke(ctx, MatchSearchService_GetMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchSearchServiceServer is the server API for MatchSearchService service.
// All implementations must embed UnimplementedMatchSearchServiceServer
// for forward compatibility.
type MatchSearchServiceServer interface {
	GetMatch(context.Context, *GetMatchRequest) (*GetMatchResponse, error)
	mustEmbedUnimplementedMatchSearchServiceServer()
}

// UnimplementedMatchSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchSearchServiceServer struct{}

func (UnimplementedMatchSearchServiceServer) GetMatch(context.Context, *GetMatchRequest) (*GetMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatch not implemented")
}
func (UnimplementedMatchSearchServiceServer) mustEmbedUnimplementedMatchSearchServiceServer() {}
func (UnimplementedMatchSearchServiceServer) testEmbeddedByValue()                            {}

// UnsafeMatchSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchSearchServiceServer will
// result in compilation errors.
type UnsafeMatchSearchServiceServer interface {
	mustEmbedUnimplementedMatchSearchServiceServer()
}

func RegisterMatchSearchServiceServer(s grpc.ServiceRegistrar, srv MatchSearchServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchSearchService_ServiceDesc, srv)
}

func _MatchSearchService_GetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchSearchServiceServer).GetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchSearchService_GetMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchSearchServiceServer).GetMatch(ctx, req.(*GetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchSearchService_ServiceDesc is the grpc.ServiceDesc for MatchSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MatchSearchService",
	HandlerType: (*MatchSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatch",
			Handler:    _MatchSearchService_GetMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
